server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
spring:
  mvc:
    static-path-pattern: /static/**
    
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://burgerking.cl6j84vpzotz.ap-northeast-2.rds.amazonaws.com/burgerking?useUnicode=true&serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: gyeongun
    password: qwer1234
  security:
    user:
      name: test
      password: 1234  
    
  web:
    resources:
      static-locations:
      - classpath:/static/
      add-mappings: true
mybatis:
  mapper-locations:
  - /mappers/*.xml

