server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
spring:
  mvc:
    static-path-pattern: /static/**
    
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/aws-gyeongun?useUnicode=true&serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: gyeongun
    password: qwer1234
    
    
  web:
    resources:
      static-locations:
      - classpath:/static/
      add-mappings: true
mybatis:
  mapper-locations:
  - /mappers/*.xml

